### ISSUE TITLE
Multi-Language

### ISSUE THREAD

**Issue by sr229** [awau/Clara#49]
Prior to our upcoming meme in March 25-April 1, [il8n](http://i18next.com/) will be supported for multi language support.

### TODO : 
- [x] add a way to track each guild's own locale for the bot. Also set a global one.
- [ ] Japanese Translation (we already know why we're doing this)
- [x] Remember that talk with TripingPC regarding porting Kizuna Ai to Discord?

**Comment by GusCaplan** [comment]
weeee i know how to do this

**Comment by sr229** [comment]
A wild snek appeared :eyes:

**Comment by Ovyerus** [comment]
Will require a database to store guild locales, and maybe user languages ~~totally not ripping off Ayana or anything :eyes:~~

**Comment by sr229** [comment]
as long it's Rethonk we're good

~~Ayana doesn't use i18n~~

**Comment by DasWolke** [comment]
~~rem does~~ °^°

**Comment by sr229** [comment]
o

~~Rem is shit tho~~

**Comment by DasWolke** [comment]
👀

**Comment by GusCaplan** [comment]
sh~~o~~its fired
